=== LMudrek/g-reviews/post-load.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "anomes": {
      "type": "integer"
    },
    "anomesdia": {
      "type": "integer"
    },
    "aplicativo": {
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "nota": {
      "type": "integer"
    },
    "idioma": {
      "type": "string"
    },
    "titulo": {
      "type": "string"
    },
    "comentario": {
      "type": "string"
    },
    "resposta": {
      "type": "string"
    },
    "dispositivo": {
      "type": "string"
    },
    "nomeVersaoApp": {
      "type": "string"
    },
    "codigoVersaoApp": {
      "type": "integer"
    },
    "ultimaModificacao": {
      "type": "object",
      "properties": {
        "comentario": {
          "type": "object",
          "properties": {
            "nano": {
              "type": "integer"
            },
            "segundos": {
              "type": "integer"
            }
          },
          "required": ["nano", "segundos"]
        },
        "resposta": {
          "type": "object",
          "properties": {
            "nano": {
              "type": "integer"
            },
            "segundos": {
              "type": "integer"
            }
          },
          "required": ["nano", "segundos"]
        }
      },
      "required": ["comentario", "resposta"]
    }
  },
  "required": [
    "anomes",
    "anomesdia",
    "aplicativo",
    "nota"
  ]
}

=== LMudrek/g-reviews/post-load.json
{
  "anomes": 202307,
  "anomesdia": 20230723,
  "aplicativo": "com.meuapp",
  "id": "abc",
  "nota": 1,
  "idioma": "PT-BR",
  "titulo": "TITULO",
  "comentario": "lorem",
  "resposta": "ipsum",
  "dispositivo": "abc98",
  "nomeVersaoApp": "1.0.0",
  "codigoVersaoApp": 1,
  "ultimaModificacao": {
    "comentario": {
      "nano": 456,
      "segundos": 123
    },
    "resposta": {
      "nano": 456,
      "segundos": 123
    }
  }
}
